blank_issues_enabled: false
contact_links:
  - name: 其他问题/疑问
    url: https://github.com/baldi233/Seewo-EasiCamera-Archive_Windows-x86-platform/discussions
    about: 如果有其他问题/疑问，请转到Discussions分区
  - name: 讨论区
